#!/bin/env python
#
# This script will create a new ticket in RT from command line. You must make sure you have installed
# rtkit and optpars before proceding. you can do #pip install urllib2_kerberos python-rtkit
# for rest read help page. you should also specify  url=testurl or url=produrl for production or staging RT.
#


from rtkit.resource import RTResource
from rtkit.authenticators import KerberosAuthenticator
from rtkit.errors import RTResourceError
from optparse import OptionParser
from rtkit import set_logging
import sys,logging,os,fileinput

logger = logging.getLogger('rtkit')
produrl = 'https://engineering.redhat.com/rt/REST/1.0/'
testurl = ''
url=produrl
resource = RTResource(url, None, None, KerberosAuthenticator)

# DEFAULT QEUE, STATUS , REQUESTOR AND OWNER
RT_Queue="eng-ops-prod"
RT_Status="new"
RT_Requestor="vmindru@redhat.com"
RT_Owner=RT_Requestor



def submit_ticket_static(content):
	try:
	    response = resource.post(path='ticket/new', payload=content,)
	    logger.info(response.parsed)
	    print response.status
	    print response.body
	except RTResourceError as e:
	    logger.error(e.response.status_int)
	    logger.error(e.response.status)
	    logger.error(e.response.parsed)

def main():
        parser = OptionParser()
        parser.add_option("-q", "--queue", dest = "queue" , default= "eng-ops-prod" , help="specify queue")
        parser.add_option("-S", "--status", dest = "status" , default= "new" , help="specify status new,resolved,open")
        parser.add_option("-r", "--requestor", dest = "requestor" , default= "none" , help="specify requestor email address e.g. vmindru@redhat.com")
        parser.add_option("-o", "--owner", dest = "owner" , default= "none" , help="specify owner email address e.g. vmindru@redhat.com ")
        parser.add_option("-s", "--subject", dest = "subject" , default= "none", help="specify subject for the new ticket, note Subject must be at least 20 characters")
#	parser.add_option("-i", "--input", dest = "input" ,default = "none", help="specify input of message body. stdin,file")
	parser.add_option("-f", "--file", dest = "file" , default = "none" , help="path to file for message body, if this parameter is not specified will read from STDIN ")
	(options, args) = parser.parse_args()
	my_options = {
			"options": {
					"Queue": options.queue,
					"Status": options.status,	
					"Requestor": options.requestor,
					"Owner": options.owner,
					"Subject": options.subject,
#					"Input": options.input,
					"File": options.file,
				}	
		}
	return my_options


def define_content(data):
	opts=data[0]["options"]
	message_body=data[1]
	content = {
	    'content': {
		'id': 'ticket/new',
	        'Subject' : opts["Subject"],
		'Text' : message_body,
	        'Queue': opts["Queue"],
		'Status': opts["Status"],
		'Requestor': opts["Requestor"],
		'Owner': opts["Owner"],
	    }
	}
	return content

# build_request_options - checks for invoked options. 
def build_request_options(opts):
	# Make sure we have a proper Subject.
	if len(opts["options"]["Subject"]) > 20:	
		True	
	else:	
		print "to short Subject"
		sys.exit(22)
	# Make sure the status is new,resolved or open
	if opts["options"]["Status"] in ["new","resolved","open"]:
		True
	else:
		print "Status can be [new,resolved,open] only"
		sys.exit(22)
	# Make sure we have a Requestor 
	if opts["options"]["Requestor"] == "none":
		print "Requestor email address not defined using default"
		opts["options"]["Requestor"] = 	RT_Requestor
	else:
		True
	# Make sure we have a Owner
	if opts["options"]["Owner"] == "none":
		print "Owner email address not defined using default"
		opts["options"]["Owner"] = RT_Requestor 	
	else:
		True
	
	# check if -i has been invoked, if no read from stdin if yes check if file exists and store it in 'text'
	if opts["options"]["File"] == "none":
		print "Grabing data from STDIN print __EOF__ on a new line when you are done with description"
		text=''
		for line in sys.stdin:
   			text=text+line
	else:
		if os.path.isfile(opts["options"]["File"]): 
			text=''
			for line in fileinput.input(files = opts["options"]["File"]):
				    text=text+line
		else:
			print "we doubt {} is a file".format(opts["options"]["File"])
	return opts,text

if __name__ == "__main__":
	# get opts 
	opts = main()
	# check options and prepare data for input
	data = 	build_request_options(opts)
	# prepare content object for input to RT
	content = define_content(data)
	# submit ticket and print status
	submit_ticket_static(content)






